spring:
  application:
    name: semantic
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: qwen3:8b #must allow tools; list could be found @ https://ollama.com/library 
          keep-alive: 30m 
          temperature: 0.2 

    #transformers for embedding
    model:
      embedding: transformers
    embedding:
      transformer:
        onnx:
          modelUri: classpath:onnx-output/model.onnx
          modelOutputName: token_embeddings
        tokenizer:
          uri: classpath:onnx-output/tokenizer.json
          options:
            padding: true
      
    vectorstore:
      elasticsearch:
        uris=http://localhost:9200
        index-name: operation_logs        
        initialize-schema: true        
        dimensions: 768                 
        embedding-field-name: embedding  
        similarity: dot_product      
